// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFJ3-DzU4IDxjaG3H2N5EetVh7JfkMiCY',
    appId: '1:776294409339:web:c6b2c1ff376a0b3cf4eede',
    messagingSenderId: '776294409339',
    projectId: 'attendence-app-ca292',
    authDomain: 'attendence-app-ca292.firebaseapp.com',
    storageBucket: 'attendence-app-ca292.firebasestorage.app',
    measurementId: 'G-S2HMJR18S7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzhRj_sN7CDci9_FE2RTO3jQfnrQ8fY4k',
    appId: '1:776294409339:android:1ee93f42edf181d4f4eede',
    messagingSenderId: '776294409339',
    projectId: 'attendence-app-ca292',
    storageBucket: 'attendence-app-ca292.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD217XUn1FLUSHjvy8Meoa3lmJP4NKHueI',
    appId: '1:776294409339:ios:0a2f037db58aa258f4eede',
    messagingSenderId: '776294409339',
    projectId: 'attendence-app-ca292',
    storageBucket: 'attendence-app-ca292.firebasestorage.app',
    iosBundleId: 'com.example.attendenceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD217XUn1FLUSHjvy8Meoa3lmJP4NKHueI',
    appId: '1:776294409339:ios:0a2f037db58aa258f4eede',
    messagingSenderId: '776294409339',
    projectId: 'attendence-app-ca292',
    storageBucket: 'attendence-app-ca292.firebasestorage.app',
    iosBundleId: 'com.example.attendenceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFJ3-DzU4IDxjaG3H2N5EetVh7JfkMiCY',
    appId: '1:776294409339:web:8f1a9fb072f4a6a6f4eede',
    messagingSenderId: '776294409339',
    projectId: 'attendence-app-ca292',
    authDomain: 'attendence-app-ca292.firebaseapp.com',
    storageBucket: 'attendence-app-ca292.firebasestorage.app',
    measurementId: 'G-67NX2EDZ0T',
  );
}
