// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe0Xr70m6wGKPmqTRBrJ6e3hKE6PR--tU',
    appId: '1:876697546833:web:2e9feeaceba07655278870',
    messagingSenderId: '876697546833',
    projectId: 'attendancetrackingapp-2f2fe',
    authDomain: 'attendancetrackingapp-2f2fe.firebaseapp.com',
    storageBucket: 'attendancetrackingapp-2f2fe.firebasestorage.app',
    measurementId: 'G-SYQ9JS93VJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBucgFZcqJqN9-tcBGdR3n_V323hz7S_f0',
    appId: '1:876697546833:android:4d20624084024e05278870',
    messagingSenderId: '876697546833',
    projectId: 'attendancetrackingapp-2f2fe',
    storageBucket: 'attendancetrackingapp-2f2fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVFgXxkN92ZDlvTQ0HwRckoxYWvi_939o',
    appId: '1:876697546833:ios:1dcbb3a109a66c36278870',
    messagingSenderId: '876697546833',
    projectId: 'attendancetrackingapp-2f2fe',
    storageBucket: 'attendancetrackingapp-2f2fe.firebasestorage.app',
    iosBundleId: 'com.example.attendenceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD217XUn1FLUSHjvy8Meoa3lmJP4NKHueI',
    appId: '1:776294409339:ios:0a2f037db58aa258f4eede',
    messagingSenderId: '776294409339',
    projectId: 'attendence-app-ca292',
    storageBucket: 'attendence-app-ca292.firebasestorage.app',
    iosBundleId: 'com.example.attendenceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFJ3-DzU4IDxjaG3H2N5EetVh7JfkMiCY',
    appId: '1:776294409339:web:8f1a9fb072f4a6a6f4eede',
    messagingSenderId: '776294409339',
    projectId: 'attendence-app-ca292',
    authDomain: 'attendence-app-ca292.firebaseapp.com',
    storageBucket: 'attendence-app-ca292.firebasestorage.app',
    measurementId: 'G-67NX2EDZ0T',
  );
}